name: Python Pull Request CI

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install black flake8
    - name: Flake8
      run: |
        flake8 **/*py
    - name: Black
      run: |
        black --check **/*py

  test:
    runs-on: ${{ matrix.os }}
    needs: lint
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        python-version: [3.8, 3.9, '3.10', 3.11]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install flowty
    - name: Test Knapsack (Linux)
      run: |        
        python knapsack/knapsack.py > log
        cat log
        export OBJECTIVE_VALUE=$(cat log | grep "UB     :")
        [ "$OBJECTIVE_VALUE" = "UB     :          -8373" ]
      if: startsWith(matrix.os, 'ubuntu')
    - name: Test Knapsack (Windows)
      run: |
        python knapsack/knapsack.py > log 2>&1
        type log
        findstr /b "UB     :" log > tmp.txt 2>&1
        set /P OBJECTIVE_VALUE=<tmp.txt
        IF "%OBJECTIVE_VALUE%" EQU "UB     :          -8373" (exit 0) ELSE (exit 1)
      shell: cmd
      if: startsWith(matrix.os, 'windows')
    - name: Test VRPTW (Linux)
      run: |
        python vrptw/vrptw.py > log
        cat log
        export OBJECTIVE_VALUE=$(cat log | grep "UB     :")
        [ "$OBJECTIVE_VALUE" = "UB     :          547.1" ]
      if: startsWith(matrix.os, 'ubuntu')
    - name: Test VRPTW (Windows)
      run: |
        python vrptw/vrptw.py > log 2>&1
        type log
        findstr /b "UB     :" log > tmp.txt 2>&1
        set /P OBJECTIVE_VALUE=<tmp.txt
        IF "%OBJECTIVE_VALUE%" EQU "UB     :          547.1" (exit 0) ELSE (exit 1)
      shell: cmd
      if: startsWith(matrix.os, 'windows')
    - name: Test VRPTW MIP (Linux)
      run: |
        python vrptw/vrptw_mip.py 4 > log
        cat log
        export OBJECTIVE_VALUE=$(cat log | grep "UB     :")
        [ "$OBJECTIVE_VALUE" = "UB     :           92.9" ]
      if: startsWith(matrix.os, 'ubuntu')
    - name: Test VRPTW MIP (Windows)
      run: |
        python vrptw/vrptw_mip.py 4 > log 2>&1
        type log
        findstr /b "UB     :" log > tmp.txt 2>&1
        set /P OBJECTIVE_VALUE=<tmp.txt
        IF "%OBJECTIVE_VALUE%" EQU "UB     :           92.9" (exit 0) ELSE (exit 1)
      shell: cmd
      if: startsWith(matrix.os, 'windows')
