name: Python Pull Request CI

on: [pull_request]

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install black flake8
    - name: Flake8
      run: |
        flake8 **/*py
    - name: Black
      run: |
        black **/*py

  test:
    runs-on: ${{ matrix.os }}
    needs: lint
    strategy:
      matrix:
        os:
          - ubuntu-18.04
          - ubuntu-20.04
          - windows-2019
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install cffi networkx or_datasets flowty
    - name: Test Knapsack (Linux)
      run: |        
        python knapsack/knapsack.py > log
        cat log
        export OBJECTIVE_VALUE=$(cat log | grep "UB     :")
        [ "$OBJECTIVE_VALUE" = "UB     :            -41" ]
      if: startsWith(matrix.os, 'ubuntu')
    - name: Test Knapsack (Windows)
      run: |
        python knapsack/knapsack.py > log 2>&1
        type log
        findstr /b "UB     :" log > tmp.txt 2>&1
        set /P OBJECTIVE_VALUE=<tmp.txt
        IF "%OBJECTIVE_VALUE%" EQU "UB     :            -41" (exit 0) ELSE (exit 1)
      shell: cmd
      if: startsWith(matrix.os, 'windows')
    - name: Test VRPTW (Linux)
      run: |
        python vrptw/vrptw.py > log
        cat log
        export OBJECTIVE_VALUE=$(cat log | grep "UB     :")
        [ "$OBJECTIVE_VALUE" = "UB     :          547.1" ]
      if: startsWith(matrix.os, 'ubuntu')
    - name: Test VRPTW (Windows)
      run: |
        python vrptw/vrptw.py > log 2>&1
        type log
        findstr /b "UB     :" log > tmp.txt 2>&1
        set /P OBJECTIVE_VALUE=<tmp.txt
        IF "%OBJECTIVE_VALUE%" EQU "UB     :          547.1" (exit 0) ELSE (exit 1)
      shell: cmd
      if: startsWith(matrix.os, 'windows')
    - name: Test VRPTW MIP (Linux)
      run: |
        python vrptw/vrptw_mip.py 4 > log
        cat log
        export OBJECTIVE_VALUE=$(cat log | grep "UB     :")
        [ "$OBJECTIVE_VALUE" = "UB     :           92.9" ]
      if: startsWith(matrix.os, 'ubuntu')
    - name: Test VRPTW MIP (Windows)
      run: |
        python vrptw/vrptw_mip.py 4 > log 2>&1
        type log
        findstr /b "UB     :" log > tmp.txt 2>&1
        set /P OBJECTIVE_VALUE=<tmp.txt
        IF "%OBJECTIVE_VALUE%" EQU "UB     :           92.9" (exit 0) ELSE (exit 1)
      shell: cmd
      if: startsWith(matrix.os, 'windows')
    - name: Test Linerlib (Linux)
      run: |
        python linerlib/time_constrained_mcf.py > log
        cat log
        export OBJECTIVE_VALUE=$(cat log | grep "UB     :")
        [ "$OBJECTIVE_VALUE" = "UB     :         129200" ]
      if: startsWith(matrix.os, 'ubuntu')
    - name: Test Linerlib (Windows)
      run: |
        python linerlib/time_constrained_mcf.py > log 2>&1
        type log
        findstr /b "UB     :" log > tmp.txt 2>&1
        set /P OBJECTIVE_VALUE=<tmp.txt
        IF "%OBJECTIVE_VALUE%" EQU "UB     :         129200" (exit 0) ELSE (exit 1)
      shell: cmd
      if: startsWith(matrix.os, 'windows')
    - name: Test with Xpress (Linux)
      run: |
        pip install xpress
        export XPRESSDIR=$(python -c "import pathlib; import site; print(pathlib.Path([p for p in site.getsitepackages() if p.endswith('site-packages')][0], 'xpress'))")
        export XPRESS=$XPRESSDIR/license
        export LD_LIBRARY_PATH=$XPRESSDIR/lib:$LD_LIBRARY_PATH
        eval "(cd $XPRESSDIR/license && ln -s community-xpauth.xpr xpauth.xpr)"
        eval "(cd $XPRESSDIR/lib && ln -s libxprs.so.37.01 libxprs.so)"
        python xpress/xpress.py > log
        cat log
        export OBJECTIVE_VALUE=$(cat log | grep -a "UB     :")
        [ "$OBJECTIVE_VALUE" = "UB     :         -122.5" ]
      if: startsWith(matrix.os, 'ubuntu')
    - name: Test with Windows (Windows)
      run: |
        pip install xpress
        python -c "import pathlib; import site; print(pathlib.Path([p for p in site.getsitepackages() if p.endswith('site-packages')][0], 'xpress'))" > tmp.txt
        set /P XPRESSDIR=<tmp.txt
        set PATH=%XPRESSDIR%\lib;%PATH%
        copy %XPRESSDIR%\license\community-xpauth.xpr %XPRESSDIR%\lib\xpauth.xpr
        python xpress/xpress.py > log 2>&1
        type log
        findstr /b "UB     :" log > tmp.txt 2>&1
        set /P OBJECTIVE_VALUE=<tmp.txt
        IF "%OBJECTIVE_VALUE%" EQU "UB     :         -122.5" (exit 0) ELSE (exit 1)
      shell: cmd
      if: startsWith(matrix.os, 'windows')
