name: Python Pull Request CI

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install black flake8
    - name: Flake8
      run: |
        flake8 **/*py
    - name: Black
      run: |
        black --check **/*py

  test-knapsack:
    runs-on: ${{ matrix.os }}
    needs: lint
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        python-version: [3.12, 3.9, '3.10', 3.11]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install flowty
    - name: Test Knapsack (Linux)
      run: |        
        python v1/knapsack/knapsack.py > log
        cat log
        export OBJECTIVE_VALUE=$(cat log | grep "UB     :")
        [ "$OBJECTIVE_VALUE" = "UB     :          -8373" ]
      if: startsWith(matrix.os, 'ubuntu')
    - name: Test Knapsack (Windows)
      run: |
        python v1/knapsack/knapsack.py > log 2>&1
        type log
        findstr /b "UB     :" log > tmp.txt 2>&1
        set /P OBJECTIVE_VALUE=<tmp.txt
        IF "%OBJECTIVE_VALUE%" EQU "UB     :          -8373" (exit 0) ELSE (exit 1)
      shell: cmd
      if: startsWith(matrix.os, 'windows')
    - name: Test Knapsack MIP (Linux)
      run: |        
        python v1/knapsack/knapsack_mip.py > log
        cat log
        export OBJECTIVE_VALUE=$(cat log | grep "UB     :")
        [ "$OBJECTIVE_VALUE" = "UB     :          -8373" ]
      if: startsWith(matrix.os, 'ubuntu')
    - name: Test Knapsack MIP (Windows)
      run: |
        python v1/knapsack/knapsack_mip.py > log 2>&1
        type log
        findstr /b "UB     :" log > tmp.txt 2>&1
        set /P OBJECTIVE_VALUE=<tmp.txt
        IF "%OBJECTIVE_VALUE%" EQU "UB     :          -8373" (exit 0) ELSE (exit 1)
      shell: cmd
      if: startsWith(matrix.os, 'windows')

  test-vrptw:
    runs-on: ${{ matrix.os }}
    needs: lint
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        python-version: [3.12, 3.9, '3.10', 3.11]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install flowty
    - name: Test vrptw (Linux)
      run: |
        python v1/vrptw/vrptw.py > log
        cat log
        export OBJECTIVE_VALUE=$(cat log | grep "UB     :")
        [ "$OBJECTIVE_VALUE" = "UB     :           1913" ]
      if: startsWith(matrix.os, 'ubuntu')
    - name: Test vrptw (Windows)
      run: |
        python v1/vrptw/vrptw.py > log 2>&1
        type log
        findstr /b "UB     :" log > tmp.txt 2>&1
        set /P OBJECTIVE_VALUE=<tmp.txt
        IF "%OBJECTIVE_VALUE%" EQU "UB     :           1913" (exit 0) ELSE (exit 1)
      shell: cmd
      if: startsWith(matrix.os, 'windows')
    - name: Test vrptw MIP (Linux)
      run: |
        python v1/vrptw/vrptw_mip.py > log
        cat log
        export OBJECTIVE_VALUE=$(cat log | grep "UB     :")
        [ "$OBJECTIVE_VALUE" = "UB     :           1913" ]
      if: startsWith(matrix.os, 'ubuntu')
    - name: Test vrptw MIP (Windows)
      run: |
        python v1/vrptw/vrptw_mip.py > log 2>&1
        type log
        findstr /b "UB     :" log > tmp.txt 2>&1
        set /P OBJECTIVE_VALUE=<tmp.txt
        IF "%OBJECTIVE_VALUE%" EQU "UB     :           1913" (exit 0) ELSE (exit 1)
      shell: cmd
      if: startsWith(matrix.os, 'windows')

  test-mcf:
    runs-on: ${{ matrix.os }}
    needs: lint
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        python-version: [3.12, 3.9, '3.10', 3.11]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install flowty
    - name: Test mcf (Linux)
      run: |
        python v1/mcf/mcf.py > log
        cat log
        export OBJECTIVE_VALUE=$(cat log | grep "UB     :")
        [ "$OBJECTIVE_VALUE" = "UB     :         827319" ]
      if: startsWith(matrix.os, 'ubuntu')
    - name: Test mcf (Windows)
      run: |
        python v1/mcf/mcf.py > log 2>&1
        type log
        findstr /b "UB     :" log > tmp.txt 2>&1
        set /P OBJECTIVE_VALUE=<tmp.txt
        IF "%OBJECTIVE_VALUE%" EQU "UB     :         827319" (exit 0) ELSE (exit 1)
      shell: cmd
      if: startsWith(matrix.os, 'windows')
