name: Python Pull Request CI

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install black flake8
    - name: Flake8
      run: |
        flake8 v2/**/*py
    - name: Black
      run: |
        black --check **/**/*py

  test-vrptw:
    runs-on: ${{ matrix.os }}
    needs: lint
    strategy:
      matrix:
        os:
          - ubuntu-latest
        python-version: [3.12, 3.9, '3.10', 3.11]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install flowty
    - name: Test vrptw (Linux)
      run: |
        python v2/vrptw/vrptw.py > log
        cat log
        export OBJECTIVE_VALUE=$(cat log | grep "Cost ")
        [ "$OBJECTIVE_VALUE" = "Cost 1913" ]

  test-mcf:
    runs-on: ${{ matrix.os }}
    needs: lint
    strategy:
      matrix:
        os:
          - ubuntu-latest
        python-version: [ 3.12, 3.9, '3.10', 3.11 ]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install flowty
    - name: Test mcf (Linux)
      run: |
        python v2/mcf/mcf.py > log
        cat log
        export OBJECTIVE_VALUE=$(cat log | grep "Cost ")
        [ "$OBJECTIVE_VALUE" = "Cost 481982340.0" ]
